import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { i18n, Locale } from "@/i18n-config";
import { getDictionary } from "@/get-dictionary";
import { Footer } from "./components/footer";
import { HeaderNavigationBar } from "./components/header-navigation-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}) {
  const params = await props.params;
  const { children } = props;
  const dictionary = await getDictionary(params.lang);

  return (
    <>
      <html lang={params.lang} suppressHydrationWarning>
        <head />
        <body className="flex flex-col min-h-screen bg-background">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <HeaderNavigationBar dictionary={dictionary.header} />
            <div className="flex flex-1 justify-center">{children}</div>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
